app = "spontany-socket"

[deploy]
  strategy = "immediate"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 3001
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0

# 반드시 추가! (WebSocket 트래픽 허용)
[[services.http_checks]]
  interval = "10s"
  timeout = "2s"
  method = "get"
  path = "/socket.io/"
  protocol = "http"
  grace_period = "5s"
  restart_limit = 0